# Generated by Django 4.1.1 on 2023-05-26 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_snippet_lang'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='language',
            name='short_name',
        ),
    ]
